# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodCompra', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=30)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('Cantidad', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumF', models.IntegerField()),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Cantidad', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoF', models.IntegerField()),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=30)),
                ('Fecha_entrada', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=30)),
                ('PrecioU', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=40)),
                ('Telefono', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=30)),
                ('Tipo', models.CharField(choices=[('U', 'usuario'), ('A', 'administrador')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=30)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('CodFa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppFarma.Farmaceutico')),
                ('CodFact', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppFarma.Factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='CodP',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppFarma.Producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='codProd',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppFarma.Producto'),
        ),
    ]
