# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFarma', '0003_perfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfiles',
        ),
    ]
